name: Prettier
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            pnpm prettier --write "**/*.{js,ts,tsx}"
          else
            pnpm prettier --check "**/*.{js,ts,tsx}"
          fi
